# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tes

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    - name: Use Node.js v23
      uses: actions/setup-node@v4
      with:
        node-version: 23
    - name: Instal MPN Modules    
      run: npm install
    - name: Start Backend
      run: npm run server-be &
    - name: Start Frontend
      run: npm run start-fe &
    - name: Execute Playwrite Update
      run:  npx playwright install   
    - name: Start UI Tests
      run: npm run test-ui
